# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llamaindex-mcp-nbdev',
                'doc_host': 'https://rehanali53.github.io',
                'git_url': 'https://github.com/rehanali53/llamaindex-mcp-nbdev',
                'lib_path': 'llamaindex_mcp_nbdev'},
  'syms': { 'llamaindex_mcp_nbdev.core': { 'llamaindex_mcp_nbdev.core.SQLiteMCPServer': ( 'core.html#sqlitemcpserver',
                                                                                          'llamaindex_mcp_nbdev/core.py'),
                                           'llamaindex_mcp_nbdev.core.SQLiteMCPServer.__init__': ( 'core.html#sqlitemcpserver.__init__',
                                                                                                   'llamaindex_mcp_nbdev/core.py'),
                                           'llamaindex_mcp_nbdev.core.SQLiteMCPServer._setup_tools': ( 'core.html#sqlitemcpserver._setup_tools',
                                                                                                       'llamaindex_mcp_nbdev/core.py'),
                                           'llamaindex_mcp_nbdev.core.SQLiteMCPServer.run': ( 'core.html#sqlitemcpserver.run',
                                                                                              'llamaindex_mcp_nbdev/core.py'),
                                           'llamaindex_mcp_nbdev.core.init_db': ('core.html#init_db', 'llamaindex_mcp_nbdev/core.py'),
                                           'llamaindex_mcp_nbdev.core.main': ('core.html#main', 'llamaindex_mcp_nbdev/core.py')}}}
