# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llamaindex-mcp-nbdev',
                'doc_host': 'https://rehanali53.github.io',
                'git_url': 'https://github.com/rehanali53/llamaindex-mcp-nbdev',
                'lib_path': 'llamaindex_mcp_nbdev'},
  'syms': {'llamaindex_mcp_nbdev.core': {'llamaindex_mcp_nbdev.core.foo': ('core.html#foo', 'llamaindex_mcp_nbdev/core.py')}}}
