# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_server.ipynb.

# %% auto 0
__all__ = ['run_server']

# %% ../nbs/01_server.ipynb 1
from llamaindex_mcp_nbdev.core import SQLiteMCPServer, main
import argparse

# %% ../nbs/01_server.ipynb 2
# Server Script
def run_server():
    """Run the MCP server with command line interface."""
    main()

if __name__ == "__main__":
    run_server()
